//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobapplicant
    {
        public int Jobseekerid { get; set; }
        public string JobSeekername { get; set; }
        public string JobseekerEmail { get; set; }
        public string JobseekerCity { get; set; }
        public string JobSeekeruniversity { get; set; }
    }
}
